name: finance
description: A new Dart package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

#dependencies:
#  flutter:
#    sdk: flutter

dev_dependencies:
  test: '>=1.3.0 <1.6.8'
